project:
  type: website
  output-dir: docs

website:
  title: "Tarificación Telemática"
  navbar:
    left:
      - href: index.qmd
        text: Introducción
      - href: about.qmd
        text: 1. Ing. de Características

  page-footer:
    right: "Angel Colmenares 2025"
    left: "Actuarial Insurtech: Tarificacion Telematica"

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    toc: true

